# Proyecto Integrador - Etapa 1

## Identificación, recopilación y preparación de los datos

### DataCo Smart Supply Chain

En este notebook se realizará la exploración, limpieza y transformación del conjunto de datos seleccionado para el Proyecto Integrador.

In [4]:
import pandas as pd
import os

In [5]:
print(os.getcwd())

/Users/sashamitchel1123/Downloads/DataCo SMART SUPPLY CHAIN FOR BIG DATA ANALYSIS

In [6]:
os.listdir()

['tokenized_access_logs.csv',
 'proyecto_integrador_etapa1.ipynb',
 'DataCoSupplyChainDataset.csv',
 'DescriptionDataCoSupplyChain.csv']

## 1. Carga del conjunto de datos

Se carga el archivo principal DataCoSupplyChainDataset.csv utilizando Pandas para comenzar con la revisión y preparación de los datos.

In [8]:
df = pd.read_csv(
    "DataCoSupplyChainDataset.csv",
    encoding="latin1",
    low_memory=False
)

In [9]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [10]:
df.shape

(180519, 53)

## 2. Revisión de la estructura y tipos de datos

Se revisa la estructura general del conjunto de datos para identificar los tipos de datos asignados a cada variable y detectar posibles transformaciones necesarias antes del análisis.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [14]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

## 3. Identificación de valores faltantes

Se revisa la presencia de valores faltantes en cada variable del conjunto de datos para identificar aquellas columnas que requieren algún tratamiento antes del análisis.

In [15]:
valores_faltantes = df.isnull().sum().sort_values(ascending=False)

valores_faltantes

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Type                                  0
Order Profit Per Order                0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
order date (DateOrders)               0
Order State                           0
Order Status                          0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Order Id                              0
Order Country                         0
Order Customer Id                     0
Customer Fname                        0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Id                           0
Days for shipping (real)              0
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Shipping Mode                         0
dtype: int64

In [16]:
valores_faltantes[valores_faltantes > 0]

Product Description    180519
Order Zipcode          155679
Customer Lname              8
Customer Zipcode            3
dtype: int64

In [17]:
resumen_faltantes = pd.DataFrame({
    "Valores faltantes": df.isnull().sum(),
    "Porcentaje (%)": (df.isnull().mean() * 100).round(4)
})

resumen_faltantes = resumen_faltantes[
    resumen_faltantes["Valores faltantes"] > 0
].sort_values("Porcentaje (%)", ascending=False)

resumen_faltantes

                     Valores faltantes  Porcentaje (%)
Product Description             180519        100.0000
Order Zipcode                   155679         86.2397
Customer Lname                       8          0.0044
Customer Zipcode                     3          0.0017

## 4. Identificación de registros duplicados

Se revisa la existencia de registros duplicados dentro del conjunto de datos para determinar si existen observaciones repetidas que puedan afectar el análisis.

In [18]:
df.duplicated().sum()

0

## 5. Revisión estadística inicial

Se realiza una revisión descriptiva de las variables numéricas para conocer sus principales características, como valores mínimos, máximos, promedio y dispersión antes de realizar las transformaciones de los datos.

In [19]:
estadisticas = df.describe(include="number").T.round(2)

estadisticas

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.50,1.62,0.00,2.00,3.00,5.00,6.00
Days for shipment (scheduled),180519.0,2.93,1.37,0.00,2.00,4.00,4.00,4.00
Benefit per order,180519.0,21.97,104.43,-4274.98,7.00,31.52,64.80,911.80
Sales per customer,180519.0,183.11,120.04,7.49,104.38,163.99,247.40,1939.99
Late_delivery_risk,180519.0,0.55,0.50,0.00,0.00,1.00,1.00,1.00
Category Id,180519.0,31.85,15.64,2.00,18.00,29.00,45.00,76.00
Customer Id,180519.0,6691.38,4162.92,1.00,3258.50,6457.00,9779.00,20757.00
Customer Zipcode,180516.0,35921.13,37542.46,603.00,725.00,19380.00,78207.00,99205.00
Department Id,180519.0,5.44,1.63,2.00,4.00,5.00,7.00,12.00
Latitude,180519.0,29.72,9.81,-33.94,18.27,33.14,39.28,48.78
Longitude,180519.0,-84.92,21.43,-158.03,-98.45,-76.85,-66.37,115.26
Order Customer Id,180519.0,6691.38,4162.92,1.00,3258.50,6457.00,9779.00,20757.00
Order Id,180519.0,36221.89,21045.38,1.00,18057.00,36140.00,54144.00,77204.00
Order Item Cardprod Id,180519.0,692.51,336.45,19.00,403.00,627.00,1004.00,1363.00
Order Item Discount,180519.0,20.66,21.80,0.00,5.40,14.00,29.99,500.00
Order Item Discount Rate,180519.0,0.10,0.07,0.00,0.04,0.10,0.16,0.25
Order Item Id,180519.0,90260.00,52111.49,1.00,45130.50,90260.00,135389.50,180519.00
Order Item Product Price,180519.0,141.23,139.73,9.99,50.00,59.99,199.99,1999.99
Order Item Profit Ratio,180519.0,0.12,0.47,-2.75,0.08,0.27,0.36,0.50
Order Item Quantity,180519.0,2.13,1.45,1.00,1.00,1.00,3.00,5.00
Sales,180519.0,203.77,132.27,9.99,119.98,199.92,299.95,1999.99
Order Item Total,180519.0,183.11,120.04,7.49,104.38,163.99,247.40,1939.99
Order Profit Per Order,180519.0,21.97,104.43,-4274.98,7.00,31.52,64.80,911.80
Order Zipcode,24840.0,55426.13,31919.28,1040.00,23464.00,59405.00,90008.00,99301.00
Product Card Id,180519.0,692.51,336.45,19.00,403.00,627.00,1004.00,1363.00
Product Category Id,180519.0,31.85,15.64,2.00,18.00,29.00,45.00,76.00
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,141.23,139.73,9.99,50.00,59.99,199.99,1999.99
Product Status,180519.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [20]:
variables_analisis = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Benefit per order",
    "Sales per customer",
    "Order Item Discount",
    "Order Item Product Price",
    "Order Item Quantity",
    "Sales"
]

df[variables_analisis].describe().T.round(2)

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.50,1.62,0.00,2.00,3.00,5.00,6.00
Days for shipment (scheduled),180519.0,2.93,1.37,0.00,2.00,4.00,4.00,4.00
Benefit per order,180519.0,21.97,104.43,-4274.98,7.00,31.52,64.80,911.80
Sales per customer,180519.0,183.11,120.04,7.49,104.38,163.99,247.40,1939.99
Order Item Discount,180519.0,20.66,21.80,0.00,5.40,14.00,29.99,500.00
Order Item Product Price,180519.0,141.23,139.73,9.99,50.00,59.99,199.99,1999.99
Order Item Quantity,180519.0,2.13,1.45,1.00,1.00,1.00,3.00,5.00
Sales,180519.0,203.77,132.27,9.99,119.98,199.92,299.95,1999.99

## 6. Limpieza de valores faltantes

Antes de realizar modificaciones se crea una copia del conjunto de datos original. Posteriormente se tratan las variables con una proporción elevada de valores faltantes, conservando el archivo original sin modificaciones.

In [21]:
df_limpio = df.copy()

df_limpio.shape

(180519, 53)

In [23]:
df_limpio = df_limpio.drop(
    columns=["Product Description", "Order Zipcode"]
)

df_limpio.shape

(180519, 51)

In [24]:
df_limpio.isnull().sum()[
    df_limpio.isnull().sum() > 0
]

Customer Lname      8
Customer Zipcode    3
dtype: int64

## 7. Transformación de variables de fecha

Se revisan las variables relacionadas con fechas para verificar su tipo de dato y transformarlas a un formato temporal adecuado para el análisis.

In [25]:
df_limpio[
    ["order date (DateOrders)", "shipping date (DateOrders)"]
].head()

  order date (DateOrders) shipping date (DateOrders)
0         1/31/2018 22:56             2/3/2018 22:56
1         1/13/2018 12:27            1/18/2018 12:27
2         1/13/2018 12:06            1/17/2018 12:06
3         1/13/2018 11:45            1/16/2018 11:45
4         1/13/2018 11:24            1/15/2018 11:24

In [26]:
df_limpio[
    ["order date (DateOrders)", "shipping date (DateOrders)"]
].dtypes

order date (DateOrders)       object
shipping date (DateOrders)    object
dtype: object

In [27]:
df_limpio["order date (DateOrders)"] = pd.to_datetime(
    df_limpio["order date (DateOrders)"],
    format="%m/%d/%Y %H:%M",
    errors="coerce"
)

df_limpio["shipping date (DateOrders)"] = pd.to_datetime(
    df_limpio["shipping date (DateOrders)"],
    format="%m/%d/%Y %H:%M",
    errors="coerce"
)

In [28]:
df_limpio[
    ["order date (DateOrders)", "shipping date (DateOrders)"]
].dtypes

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [29]:
df_limpio[
    ["order date (DateOrders)", "shipping date (DateOrders)"]
].isnull().sum()

order date (DateOrders)       0
shipping date (DateOrders)    0
dtype: int64

In [30]:
df_limpio.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Product Card Id',
 'Product Category Id',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

## 8. Tratamiento de valores faltantes restantes

Después de la limpieza inicial permanecen valores faltantes en las variables Customer Lname y Customer Zipcode. Debido a que estas variables no son necesarias para el objetivo principal del análisis, se eliminan del conjunto de datos en lugar de completar la información con valores que no pueden determinarse a partir de los datos disponibles.

In [31]:
df_limpio = df_limpio.drop(
    columns=["Customer Lname", "Customer Zipcode"]
)

df_limpio.shape

(180519, 49)

In [32]:
df_limpio.isnull().sum().sum()

0

In [33]:
print("Registros:", df_limpio.shape[0])
print("Columnas:", df_limpio.shape[1])
print("Valores faltantes:", df_limpio.isnull().sum().sum())

Registros: 180519
Columnas: 49
Valores faltantes: 0

## 9. Estandarización de los nombres de las variables

Se estandarizan los nombres de las columnas para facilitar su utilización durante el análisis. Se eliminan espacios innecesarios, se utilizan letras minúsculas y los espacios o caracteres especiales se sustituyen por guiones bajos.

In [34]:
columnas_antes = df_limpio.columns.tolist()

df_limpio.columns = (
    df_limpio.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[()]", "", regex=True)
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

In [35]:
comparacion_columnas = pd.DataFrame({
    "Nombre original": columnas_antes,
    "Nombre estandarizado": df_limpio.columns
})

comparacion_columnas.head(15)

                  Nombre original         Nombre estandarizado
0                            Type                         type
1        Days for shipping (real)       days_for_shipping_real
2   Days for shipment (scheduled)  days_for_shipment_scheduled
3               Benefit per order            benefit_per_order
4              Sales per customer           sales_per_customer
5                 Delivery Status              delivery_status
6              Late_delivery_risk           late_delivery_risk
7                     Category Id                  category_id
8                   Category Name                category_name
9                   Customer City                customer_city
10               Customer Country             customer_country
11                 Customer Email               customer_email
12                 Customer Fname               customer_fname
13                    Customer Id                  customer_id
14              Customer Password            customer_password

## 10. Verificación final del conjunto de datos

Se realiza una revisión final de la estructura del conjunto de datos después de los procesos de limpieza y transformación, con el propósito de comprobar que no existan valores faltantes y que los tipos de datos y nombres de variables sean adecuados para continuar con el análisis.

In [36]:
print("Registros finales:", df_limpio.shape[0])
print("Columnas finales:", df_limpio.shape[1])
print("Valores faltantes:", df_limpio.isnull().sum().sum())
print("Registros duplicados:", df_limpio.duplicated().sum())

Registros finales: 180519
Columnas finales: 49
Valores faltantes: 0
Registros duplicados: 0

In [37]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 49 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   type                         180519 non-null  object
 1   days_for_shipping_real       180519 non-null  int64
 2   days_for_shipment_scheduled  180519 non-null  int64
 3   benefit_per_order            180519 non-null  float64
 4   sales_per_customer           180519 non-null  float64
 5   delivery_status              180519 non-null  object
 6   late_delivery_risk           180519 non-null  int64
 7   category_id                  180519 non-null  int64
 8   category_name                180519 non-null  object
 9   customer_city                180519 non-null  object
 10  customer_country             180519 non-null  object
 11  customer_email               180519 non-null  object
 12  customer_fname               180519 non-null  object
 13  customer_id                  180519 non-null  int64
 14  customer_password            180519 non-null  object
 15  customer_segment             180519 non-null  object
 16  customer_state               180519 non-null  object
 17  customer_street              180519 non-null  object
 18  department_id                180519 non-null  int64
 19  department_name              180519 non-null  object
 20  latitude                     180519 non-null  float64
 21  longitude                    180519 non-null  float64
 22  market                       180519 non-null  object
 23  order_city                   180519 non-null  object
 24  order_country                180519 non-null  object
 25  order_customer_id            180519 non-null  int64
 26  order_date_dateorders        180519 non-null  datetime64[ns]
 27  order_id                     180519 non-null  int64
 28  order_item_cardprod_id       180519 non-null  int64
 29  order_item_discount          180519 non-null  float64
 30  order_item_discount_rate     180519 non-null  float64
 31  order_item_id                180519 non-null  int64
 32  order_item_product_price     180519 non-null  float64
 33  order_item_profit_ratio      180519 non-null  float64
 34  order_item_quantity          180519 non-null  int64
 35  sales                        180519 non-null  float64
 36  order_item_total             180519 non-null  float64
 37  order_profit_per_order       180519 non-null  float64
 38  order_region                 180519 non-null  object
 39  order_state                  180519 non-null  object
 40  order_status                 180519 non-null  object
 41  product_card_id              180519 non-null  int64
 42  product_category_id          180519 non-null  int64
 43  product_image                180519 non-null  object
 44  product_name                 180519 non-null  object
 45  product_price                180519 non-null  float64
 46  product_status               180519 non-null  int64
 47  shipping_date_dateorders     180519 non-null  datetime64[ns]
 48  shipping_mode                180519 non-null  object
dtypes: datetime64[ns](2), float64(12), int64(14), object(21)
memory usage: 67.5+ MB

In [38]:
df_limpio.head()

,type,days_for_shipping_real,days_for_shipment_scheduled,benefit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,customer_city,...,order_state,order_status,product_card_id,product_category_id,product_image,product_name,product_price,product_status,shipping_date_dateorders,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

## 11. Exportación del conjunto de datos preparado

Una vez finalizados los procesos de limpieza y transformación, se guarda una nueva versión del conjunto de datos en formato CSV. El archivo original se conserva sin modificaciones y la nueva versión será utilizada para continuar con la segunda etapa del Proyecto Integrador.

In [39]:
df_limpio.to_csv(
    "DataCoSupplyChainDataset_limpio.csv",
    index=False,
    encoding="utf-8"
)

In [40]:
import os

print(
    os.path.exists("DataCoSupplyChainDataset_limpio.csv")
)

True

In [41]:
print("Dimensiones del archivo exportado:", df_limpio.shape)

Dimensiones del archivo exportado: (180519, 49)